# Generated by Django 3.1.4 on 2021-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_geography_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='Corrans',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='geography',
            name='Option1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='geography',
            name='Option2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='geography',
            name='Option3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='geography',
            name='Option4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='geography',
            name='Question',
            field=models.CharField(max_length=200),
        ),
    ]
